version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
