version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/jamiewilson.app.conf:/etc/nginx/sites-enabled/jamiewilson.app.conf
      - /etc/letsencrypt/live/www.jamiewilson.app/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/www.jamiewilson.app/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf:ro
      - ./ssl-dhparams.pem:/etc/nginx/ssl/ssl-dhparams.pem:ro
    depends_on:
      - client
      - server
