name: Lint and Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm install

      # Lint and format client
      - name: Lint and format client
        run: |
          cd client
          npm install
          npm run lint -- --fix
          npm run format

      # Lint and format server
      - name: Lint and format server
        run: |
          cd server
          npm install
          npm run lint -- --fix
          npm run format
